#!/usr/bin/env bash
# Sync production trading env on every deploy — EC2 /opt/nexusquant/env often drifts stricter than code defaults.
set -euo pipefail

ENV_FILE="${1:-/opt/nexusquant/env}"

upsert() {
  local k="$1" v="$2"
  if sudo grep -q "^${k}=" "${ENV_FILE}" 2>/dev/null; then
    sudo sed -i "s|^${k}=.*|${k}=${v}|" "${ENV_FILE}"
  else
    echo "${k}=${v}" | sudo tee -a "${ENV_FILE}" >/dev/null
  fi
}

echo "==> Sync trading env (max-catch >90% mode): ${ENV_FILE}"

upsert NEXUSQUANT_BACKEND_COMMIT "${NEXUSQUANT_BACKEND_COMMIT:-unknown}"
upsert PAPER_MAX_DAILY_LOSS_AMOUNT 50000
upsert PAPER_MAX_DAILY_LOSS_PCT 10
upsert PAPER_MAX_CONSECUTIVE_LOSSES 4
upsert PAPER_MAX_CATCH_MODE true
upsert PAPER_PROFIT_FIRST_MODE true
upsert PAPER_TARGET_PROFIT_FACTOR 1.5
upsert PAPER_TARGET_WIN_RATE_PCT 45
upsert PAPER_ROLLING_CALIBRATION_TRADES 8
upsert PAPER_HIGH_CONFIDENCE_ONLY false
upsert PAPER_MIN_ENTRY_TQS 58
upsert PAPER_MOMENTUM_MIN_ENTRY_TQS 52
upsert PAPER_HIGH_CONFIDENCE_MIN_TQS 58
upsert PAPER_HIGH_CONFIDENCE_MIN_RUNNER_SCORE 68
upsert PAPER_MOMENTUM_MIN_PREMIUM_LTP 25
upsert PAPER_MOMENTUM_MAX_ENTRY_PREMIUM 175
upsert PAPER_MOMENTUM_CHASE_PREMIUM_FLOOR 165
upsert PAPER_MOMENTUM_CHASE_MAX_VELOCITY_PCT 1.0
upsert PAPER_MOMENTUM_EXPLOSION_VELOCITY_PCT 1.5
upsert PAPER_MOMENTUM_EXPLOSION_VOLUME_ACCEL 15
upsert PAPER_MOMENTUM_OVERRIDE_MIN_VELOCITY_PCT 1.5
upsert PAPER_RUNNER_BYPASS_QUALITY_GATES false
upsert PAPER_PROFIT_EXPLOSION_BYPASS false
upsert PAPER_BREADTH_FILTER_ENABLED true
upsert PAPER_DUAL_CAPITAL_ENABLED true
upsert PAPER_SCALPING_CAPITAL 150000
upsert PAPER_EXPLOSIVE_CAPITAL 350000
upsert PAPER_SCALPING_MAX_OPEN_TRADES 2
upsert PAPER_EXPLOSIVE_MAX_OPEN_TRADES 2
upsert PAPER_SCALPING_ALLOCATION_PCT 15
upsert PAPER_EXPLOSIVE_ALLOCATION_PCT 12
upsert PAPER_SCALPING_MIN_ENTRY_TQS 55
upsert PAPER_AI_ADAPTIVE_EXIT_ENABLED true
upsert PAPER_MAX_OPEN_TRADES 4
upsert PAPER_DUPLICATE_SIGNAL_COOLDOWN_SECONDS 15
upsert PAPER_MAX_CATCH_MIN_RUNNER_SCORE 70
upsert PAPER_MAX_CATCH_RUNNER_EMIT_LIMIT 4
upsert PAPER_SAME_SIDE_LOSS_COOLDOWN_SECONDS 2400
upsert EXPLOSIVE_RUNNER_SCAN_STRIKES 40
upsert EXPLOSIVE_RUNNER_MIN_SCORE 55
upsert EXPLOSIVE_RUNNER_MOMENTUM_MIN_SCORE 50
upsert EXPLOSIVE_RUNNER_MOMENTUM_PREMIUM_VELOCITY_PCT 1.5
upsert SNAPSHOT_CACHE_SECONDS 10
upsert MARKET_POLL_SECONDS 8
upsert MARKET_SNAPSHOT_POLL_SECONDS 90
upsert BACKGROUND_MARKET_MONITOR_ENABLED false
upsert BACKGROUND_MONITOR_SCHEDULE_ENABLED false

echo "==> Key trading settings:"
sudo grep -E "^(PAPER_MAX_CATCH|PAPER_MIN_ENTRY|PAPER_HIGH_CONFIDENCE|EXPLOSIVE_RUNNER|MARKET_POLL|SNAPSHOT_CACHE)" "${ENV_FILE}" | sort -u || true
