#!/usr/bin/env bash
# Sync production trading env on every deploy — EC2 /opt/nexusquant/env often drifts stricter than code defaults.
set -euo pipefail

ENV_FILE="${1:-/opt/nexusquant/env}"

upsert() {
  local k="$1" v="$2"
  if sudo grep -q "^${k}=" "${ENV_FILE}" 2>/dev/null; then
    sudo sed -i "s|^${k}=.*|${k}=${v}|" "${ENV_FILE}"
  else
    echo "${k}=${v}" | sudo tee -a "${ENV_FILE}" >/dev/null
  fi
}

echo "==> Sync trading env (ultra-elite runner + scalp-first mode): ${ENV_FILE}"

upsert NEXUSQUANT_BACKEND_COMMIT "${NEXUSQUANT_BACKEND_COMMIT:-unknown}"
upsert PAPER_MAX_DAILY_LOSS_AMOUNT 50000
upsert PAPER_MAX_DAILY_LOSS_PCT 10
upsert PAPER_MAX_CONSECUTIVE_LOSSES 4
upsert PAPER_MAX_CATCH_MODE false
upsert PAPER_ELITE_RUNNER_ONLY true
upsert PAPER_PROFIT_FIRST_MODE true
upsert PAPER_TARGET_PROFIT_FACTOR 2.5
upsert PAPER_TARGET_WIN_RATE_PCT 45
upsert PAPER_ROLLING_CALIBRATION_TRADES 8
upsert PAPER_HIGH_CONFIDENCE_ONLY true
upsert PAPER_MIN_ENTRY_TQS 58
upsert PAPER_MOMENTUM_MIN_ENTRY_TQS 52
upsert PAPER_HIGH_CONFIDENCE_MIN_TQS 86
upsert PAPER_HIGH_CONFIDENCE_MIN_RUNNER_SCORE 92
upsert PAPER_ULTRA_ELITE_MIN_RUNNER_SCORE 92
upsert PAPER_ULTRA_ELITE_MIN_VELOCITY_PCT 3
upsert PAPER_ULTRA_ELITE_MIN_VOLUME_ACCEL 30
upsert PAPER_PREFER_SCALPING true
upsert PAPER_RUNNER_START_SCALP_LOCK true
upsert PAPER_SUGGESTED_TRADE_DEDUPE true
upsert PAPER_UNIFIED_SCALP_SESSION_PROFILE true
upsert PAPER_PSYCHOLOGY_AFFECTS_SCALP_EXITS false
upsert PAPER_MOMENTUM_MIN_PREMIUM_LTP 25
upsert PAPER_MOMENTUM_MAX_ENTRY_PREMIUM 175
upsert PAPER_MOMENTUM_CHASE_PREMIUM_FLOOR 165
upsert PAPER_MOMENTUM_CHASE_MAX_VELOCITY_PCT 1.0
upsert PAPER_MOMENTUM_EXPLOSION_VELOCITY_PCT 1.5
upsert PAPER_MOMENTUM_EXPLOSION_VOLUME_ACCEL 15
upsert PAPER_MOMENTUM_OVERRIDE_MIN_VELOCITY_PCT 1.5
upsert PAPER_RUNNER_BYPASS_QUALITY_GATES false
upsert PAPER_PROFIT_EXPLOSION_BYPASS false
upsert PAPER_BREADTH_FILTER_ENABLED true
upsert PAPER_DUAL_CAPITAL_ENABLED true
upsert PAPER_SCALPING_CAPITAL 200000
upsert PAPER_EXPLOSIVE_CAPITAL 300000
upsert PAPER_SCALPING_MAX_OPEN_TRADES 3
upsert PAPER_EXPLOSIVE_MAX_OPEN_TRADES 2
upsert PAPER_SCALPING_ALLOCATION_PCT 28
upsert PAPER_EXPLOSIVE_ALLOCATION_PCT 15
upsert PAPER_RUNNER_MAX_ALLOCATION_PCT 22
upsert PAPER_SCALPING_MIN_ENTRY_TQS 52
upsert PAPER_AI_ADAPTIVE_EXIT_ENABLED true
upsert PAPER_ACS_SCALP_ENABLED true
upsert PAPER_SCALP_CONTROLLED_STOP_POINTS 3.5
upsert PAPER_SCALP_BREAKEVEN_SHIFT_POINTS 3.0
upsert PAPER_SCALP_RUNNER_ARM_POINTS 5.0
upsert PAPER_SCALP_RUNNER_MIN_LOCK_POINTS 2.5
upsert PAPER_SCALP_RUNNER_RETAIN_PCT 0.58
upsert PAPER_SCALP_RUNNER_CAP_POINTS 12
upsert PAPER_SCALP_MICRO_ARM_POINTS 4.0
upsert PAPER_SCALP_MICRO_TRAIL_POINTS 1.25
upsert PAPER_SCALP_EARLY_DECAY_SECONDS 45
upsert PAPER_SCALP_EARLY_DECAY_MIN_GAIN 0.5
upsert PAPER_SCALP_VELOCITY_MIN_PCT 2.0
upsert PAPER_SCALP_BLOCK_CLOSING_MOMENTUM false
upsert PAPER_ALL_DAY_SCALP_ENABLED true
upsert PAPER_ALWAYS_TRADE_EXPLOSIVE_RUNNERS true
upsert PAPER_ADVANCED_SCALP_ENABLED true
upsert PAPER_SCALP_REGIME_GATE_ENABLED true
upsert PAPER_SCALP_EV_GATE_ENABLED true
upsert PAPER_SCALP_EV_MIN_TRADES 8
upsert PAPER_SCALP_EV_MIN_PROFIT_FACTOR 1.0
upsert PAPER_SCALP_EV_MIN_EXPECTANCY -0.5
upsert PAPER_SCALP_ABSORPTION_GATE_ENABLED true
upsert PAPER_SCALP_CROSS_INDEX_ENABLED true
upsert PAPER_SCALP_CROSS_INDEX_MIN 2
upsert PAPER_SCALP_VOL_SCALED_ACS_ENABLED true
upsert PAPER_SCALP_ADAPTIVE_DECAY_ENABLED true
upsert PAPER_SCALP_PARTIAL_EXIT_ENABLED true
upsert PAPER_SCALP_PARTIAL_EXIT_POINTS 4.0
upsert PAPER_SCALP_PARTIAL_EXIT_PCT 0.45
upsert PAPER_SCALP_PARTIAL_REMAINDER_STOP_POINTS 2.0
upsert PAPER_SCALP_FADE_LANE_ENABLED true
upsert PAPER_SCALP_KELLY_SIZING_ENABLED true
upsert PAPER_SCALP_ML_EXIT_OVERLAY_ENABLED true
upsert PAPER_QUICK_PROFIT_ENABLED true
upsert PAPER_QUICK_PROFIT_POINTS 12
upsert PAPER_QUICK_PROFIT_MIN_LOTS 6
upsert PAPER_QUICK_PROFIT_TARGET_LOTS 10
upsert PAPER_QUICK_PROFIT_MAX_LOTS 15
upsert PAPER_QUICK_PROFIT_ALLOCATION_BOOST 1.8
upsert PAPER_QUICK_PROFIT_RISK_UNIT_POINTS 3.5
upsert PAPER_QUICK_PROFIT_RISK_BUDGET_AMOUNT 15000
upsert PAPER_QUICK_PROFIT_SIZE_RUNNERS true
upsert PAPER_MICRO_SCALP_MIN_GAIN 3
upsert PAPER_MICRO_SCALP_TRAIL_POINTS 1.25
upsert PAPER_MICRO_SCALP_GIVEBACK_PCT 0.4
upsert PAPER_RUNNER_QUICK_LOCK_SECONDS 40
upsert PAPER_TARGET_POINTS 10
upsert PAPER_BREAKEVEN_SHIFT_POINTS 5
upsert PAPER_RUNNER_TRAIL_RETAIN_PCT 45
upsert PAPER_MAX_OPEN_TRADES 4
upsert PAPER_DUPLICATE_SIGNAL_COOLDOWN_SECONDS 45
upsert PAPER_RUNNER_MIN_HOLD_SECONDS 90
upsert PAPER_MAX_CATCH_MIN_RUNNER_SCORE 88
upsert PAPER_MAX_CATCH_RUNNER_EMIT_LIMIT 2
upsert PAPER_ALWAYS_TRADE_EXPLOSIVE_RUNNERS false
upsert PAPER_SAME_SIDE_LOSS_COOLDOWN_SECONDS 2400
upsert EXPLOSIVE_RUNNER_SCAN_STRIKES 40
upsert EXPLOSIVE_RUNNER_MIN_SCORE 92
upsert EXPLOSIVE_RUNNER_MOMENTUM_MIN_SCORE 90
upsert EXPLOSIVE_RUNNER_ELITE_MIN_SCORE 92
upsert EXPLOSIVE_RUNNER_MOMENTUM_PREMIUM_VELOCITY_PCT 1.5
upsert SNAPSHOT_CACHE_SECONDS 10
upsert MARKET_POLL_SECONDS 8
upsert MARKET_SNAPSHOT_POLL_SECONDS 90
upsert BACKGROUND_MARKET_MONITOR_ENABLED false
upsert BACKGROUND_MONITOR_SCHEDULE_ENABLED false

echo "==> Key trading settings:"
sudo grep -E "^(PAPER_MAX_CATCH|PAPER_MIN_ENTRY|PAPER_HIGH_CONFIDENCE|EXPLOSIVE_RUNNER|MARKET_POLL|SNAPSHOT_CACHE)" "${ENV_FILE}" | sort -u || true
