#!/usr/bin/env bash
# Sync production trading env on every deploy — EC2 /opt/nexusquant/env often drifts stricter than code defaults.
set -euo pipefail

ENV_FILE="${1:-/opt/nexusquant/env}"

upsert() {
  local k="$1" v="$2"
  if sudo grep -q "^${k}=" "${ENV_FILE}" 2>/dev/null; then
    sudo sed -i "s|^${k}=.*|${k}=${v}|" "${ENV_FILE}"
  else
    echo "${k}=${v}" | sudo tee -a "${ENV_FILE}" >/dev/null
  fi
}

echo "==> Sync trading env (ultra-elite runner + scalp-first mode): ${ENV_FILE}"

upsert NEXUSQUANT_BACKEND_COMMIT "${NEXUSQUANT_BACKEND_COMMIT:-unknown}"
upsert PAPER_MAX_DAILY_LOSS_AMOUNT 50000
upsert PAPER_MAX_DAILY_LOSS_PCT 10
upsert PAPER_MAX_CONSECUTIVE_LOSSES 4
upsert PAPER_MAX_CATCH_MODE false
upsert PAPER_ELITE_RUNNER_ONLY true
upsert PAPER_PROFIT_FIRST_MODE true
upsert PAPER_TARGET_PROFIT_FACTOR 2.5
upsert PAPER_TARGET_WIN_RATE_PCT 45
upsert PAPER_ROLLING_CALIBRATION_TRADES 8
upsert PAPER_HIGH_CONFIDENCE_ONLY true
upsert PAPER_MIN_ENTRY_TQS 58
upsert PAPER_MOMENTUM_MIN_ENTRY_TQS 52
upsert PAPER_HIGH_CONFIDENCE_MIN_TQS 86
upsert PAPER_HIGH_CONFIDENCE_MIN_RUNNER_SCORE 92
upsert PAPER_ULTRA_ELITE_MIN_RUNNER_SCORE 92
upsert PAPER_ULTRA_ELITE_MIN_VELOCITY_PCT 3
upsert PAPER_ULTRA_ELITE_MIN_VOLUME_ACCEL 30
upsert PAPER_PREFER_SCALPING true
upsert PAPER_RUNNER_START_SCALP_LOCK true
upsert PAPER_SUGGESTED_TRADE_DEDUPE true
upsert PAPER_UNIFIED_SCALP_SESSION_PROFILE true
upsert PAPER_PSYCHOLOGY_AFFECTS_SCALP_EXITS false
upsert PAPER_MOMENTUM_MIN_PREMIUM_LTP 25
upsert PAPER_MOMENTUM_MAX_ENTRY_PREMIUM 175
upsert PAPER_MOMENTUM_CHASE_PREMIUM_FLOOR 165
upsert PAPER_MOMENTUM_CHASE_MAX_VELOCITY_PCT 1.0
upsert PAPER_MOMENTUM_EXPLOSION_VELOCITY_PCT 1.5
upsert PAPER_MOMENTUM_EXPLOSION_VOLUME_ACCEL 15
upsert PAPER_MOMENTUM_OVERRIDE_MIN_VELOCITY_PCT 1.5
upsert PAPER_RUNNER_BYPASS_QUALITY_GATES false
upsert PAPER_PROFIT_EXPLOSION_BYPASS false
upsert PAPER_BREADTH_FILTER_ENABLED true
upsert PAPER_DUAL_CAPITAL_ENABLED true
upsert PAPER_SCALPING_CAPITAL 200000
upsert PAPER_EXPLOSIVE_CAPITAL 300000
upsert PAPER_SCALPING_MAX_OPEN_TRADES 3
upsert PAPER_EXPLOSIVE_MAX_OPEN_TRADES 1
upsert PAPER_SCALPING_ALLOCATION_PCT 32
upsert PAPER_EXPLOSIVE_ALLOCATION_PCT 15
upsert PAPER_RUNNER_MAX_ALLOCATION_PCT 22
upsert PAPER_SCALPING_MIN_ENTRY_TQS 52
upsert PAPER_SCALP_RELAXED_GATES true
upsert PAPER_OPEN_DRIVE_MOMENTUM_CATCH true
upsert PAPER_MOMENTUM_BURST_MIN_RUNNER_SCORE 65
upsert PAPER_MOMENTUM_BURST_MIN_VELOCITY_PCT 2.0
upsert PAPER_MOMENTUM_BURST_MIN_VOLUME_ACCEL 12
upsert PAPER_VERTICAL_SURGE_VELOCITY_PCT 6.0
upsert PAPER_PROFIT_EXPLOSION_BYPASS true
upsert OPTION_VELOCITY_WINDOW_SECONDS 8
upsert PAPER_SCALP_RELAXED_SESSIONS "MIDDAY_CHOP,NORMAL,OPEN_DRIVE"
upsert PAPER_SCALP_RELAXED_MIN_RUNNER_SCORE 65
upsert PAPER_SCALP_RELAXED_MIN_TQS 48
upsert PAPER_AI_ADAPTIVE_EXIT_ENABLED true
upsert PAPER_ACS_SCALP_ENABLED true
upsert PAPER_SCALP_CONTROLLED_STOP_POINTS 3.0
upsert PAPER_SCALP_BREAKEVEN_SHIFT_POINTS 2.5
upsert PAPER_SCALP_RUNNER_ARM_POINTS 3.5
upsert PAPER_SCALP_RUNNER_MIN_LOCK_POINTS 2.0
upsert PAPER_SCALP_RUNNER_RETAIN_PCT 0.65
upsert PAPER_SCALP_RUNNER_CAP_POINTS 10
upsert PAPER_SCALP_MICRO_ARM_POINTS 1.2
upsert PAPER_SCALP_MICRO_TRAIL_POINTS 0.5
upsert PAPER_SCALP_EARLY_DECAY_SECONDS 35
upsert PAPER_SCALP_EARLY_DECAY_MIN_GAIN 0.35
upsert PAPER_SCALP_VELOCITY_MIN_PCT 2.0
upsert PAPER_SCALP_BLOCK_CLOSING_MOMENTUM false
upsert PAPER_ALL_DAY_SCALP_ENABLED true
upsert PAPER_ALWAYS_TRADE_EXPLOSIVE_RUNNERS true
upsert PAPER_ADVANCED_SCALP_ENABLED true
upsert PAPER_SCALP_REGIME_GATE_ENABLED true
upsert PAPER_SCALP_EV_GATE_ENABLED true
upsert PAPER_SCALP_EV_MIN_TRADES 8
upsert PAPER_SCALP_EV_MIN_PROFIT_FACTOR 1.0
upsert PAPER_SCALP_EV_MIN_EXPECTANCY -0.5
upsert PAPER_SCALP_ABSORPTION_GATE_ENABLED true
upsert PAPER_SCALP_CROSS_INDEX_ENABLED true
upsert PAPER_SCALP_CROSS_INDEX_MIN 1
upsert PAPER_SCALP_VOL_SCALED_ACS_ENABLED true
upsert PAPER_SCALP_ADAPTIVE_DECAY_ENABLED false
upsert PAPER_SCALP_PARTIAL_EXIT_ENABLED false
upsert PAPER_SCALP_PARTIAL_EXIT_POINTS 5.5
upsert PAPER_SCALP_PARTIAL_EXIT_PCT 0.60
upsert PAPER_SCALP_PARTIAL_REMAINDER_STOP_POINTS 2.0
upsert PAPER_SCALP_RELUCTANT_PROFIT_ENABLED false
upsert PAPER_SCALP_MICRO_PARTIAL_POINTS 1.2
upsert PAPER_SCALP_MICRO_PARTIAL_PCT 0.50
upsert PAPER_SCALP_GRIND_PROFIT_SECONDS 30
upsert PAPER_SCALP_GRIND_PROFIT_MIN_GAIN 0.5
upsert PAPER_SCALP_STALE_GIVEBACK_POINTS 0.5
upsert PAPER_SCALP_STALE_MIN_BEST_GAIN 1.0
upsert PAPER_SCALP_STALE_MIN_UNREALIZED 0.3
upsert PAPER_SCALP_FADE_LANE_ENABLED true
upsert PAPER_SCALP_KELLY_SIZING_ENABLED true
upsert PAPER_SCALP_ML_EXIT_OVERLAY_ENABLED false
upsert PAPER_ADAPTIVE_SCALP_LOCK_MIN_GAIN_POINTS 4.0
upsert PAPER_ACS_QUICK_PROFIT_POINTS 6.0
upsert PAPER_SCALP_TIME_LOCK_SECONDS 75
upsert PAPER_SCALP_TIME_LOCK_MIN_GAIN 2.5
upsert PAPER_SCALP_CHASE_PREMIUM_FLOOR 85
upsert PAPER_SCALP_CHASE_MIN_VELOCITY_PCT 3.5
upsert PAPER_SCALP_RED_STREAK_PAUSE_LOSSES 2
upsert PAPER_SCALP_RED_STREAK_MIN_PF 0.5
upsert PAPER_SCALP_RED_STREAK_ROLLING_TRADES 3
upsert PAPER_SCALP_RED_STREAK_DEAD_ENTRIES 2
upsert PAPER_SCALP_LOSS_STREAK_LOT_CAP 8
upsert PAPER_SCALP_LOSS_STREAK_LOT_CAP_AFTER 2
upsert PAPER_SCALP_LOSS_STREAK_PF_CAP 1.0
upsert PAPER_SCALP_MIN_ENTRY_VELOCITY_PCT 1.0
upsert PAPER_SCALP_CHOP_BREADTH_LOW 45
upsert PAPER_SCALP_CHOP_BREADTH_HIGH 55
upsert PAPER_SCALP_WIN_STREAK_LOT_BOOST 1.35
upsert PAPER_DUAL_STRATEGY_ENABLED true
upsert PAPER_SIMPLE_PROFIT_MODE false
upsert PAPER_SIMPLE_MIN_VELOCITY_PCT 2.0
upsert PAPER_SIMPLE_MIN_RUNNER_SCORE 72
upsert PAPER_SIMPLE_TARGET_POINTS 4.0
upsert PAPER_SIMPLE_STOP_POINTS 3.0
upsert PAPER_SIMPLE_MIN_HOLD_SECONDS 30
upsert PAPER_SIMPLE_MAX_HOLD_SECONDS 180
upsert PAPER_SIMPLE_TRAIL_ARM_POINTS 2.0
upsert PAPER_SIMPLE_TRAIL_RETAIN_PCT 0.50
upsert PAPER_SIMPLE_MIN_LOTS 2
upsert PAPER_SIMPLE_TARGET_LOTS 4
upsert PAPER_SIMPLE_MAX_LOTS 6
upsert PAPER_SIMPLE_MAX_LOSS_INR 2500
upsert PAPER_SIMPLE_EMERGENCY_LOSS_INR 4000
upsert PAPER_TRADE_MASTERMIND_ENABLED false
upsert PAPER_MASTERMIND_RUNNER_TARGET_POINTS 6.0
upsert PAPER_MASTERMIND_MIN_HOLD_SECONDS 45
upsert PAPER_MASTERMIND_MICRO_BURST_TARGET 2.0
upsert PAPER_MASTERMIND_MAX_STOP_POINTS 6.0
upsert PAPER_MASTERMIND_MIN_STOP_POINTS 2.0
upsert PAPER_MASTERMIND_MICRO_BURST_LOT_MULT 1.45
upsert PAPER_QUICK_PROFIT_ENABLED true
upsert PAPER_QUICK_PROFIT_POINTS 12
upsert PAPER_QUICK_PROFIT_MIN_LOTS 8
upsert PAPER_QUICK_PROFIT_TARGET_LOTS 14
upsert PAPER_QUICK_PROFIT_MAX_LOTS 24
upsert PAPER_QUICK_PROFIT_ALLOCATION_BOOST 2.1
upsert PAPER_QUICK_PROFIT_RISK_UNIT_POINTS 3.0
upsert PAPER_QUICK_PROFIT_RISK_BUDGET_AMOUNT 35000
upsert PAPER_QUICK_PROFIT_SIZE_RUNNERS true
upsert PAPER_MICRO_SCALP_MIN_GAIN 3
upsert PAPER_MICRO_SCALP_TRAIL_POINTS 1.25
upsert PAPER_MICRO_SCALP_GIVEBACK_PCT 0.4
upsert PAPER_RUNNER_QUICK_LOCK_SECONDS 40
upsert PAPER_TARGET_POINTS 10
upsert PAPER_BREAKEVEN_SHIFT_POINTS 5
upsert PAPER_RUNNER_TRAIL_RETAIN_PCT 45
upsert PAPER_MAX_OPEN_TRADES 4
upsert PAPER_DUPLICATE_SIGNAL_COOLDOWN_SECONDS 45
upsert PAPER_RUNNER_MIN_HOLD_SECONDS 90
upsert PAPER_MAX_CATCH_MIN_RUNNER_SCORE 88
upsert PAPER_MAX_CATCH_RUNNER_EMIT_LIMIT 2
upsert PAPER_SAME_SIDE_LOSS_COOLDOWN_SECONDS 1200
upsert EXPLOSIVE_RUNNER_SCAN_STRIKES 40
upsert EXPLOSIVE_RUNNER_MIN_SCORE 92
upsert EXPLOSIVE_RUNNER_MOMENTUM_MIN_SCORE 90
upsert EXPLOSIVE_RUNNER_ELITE_MIN_SCORE 92
upsert EXPLOSIVE_RUNNER_MOMENTUM_PREMIUM_VELOCITY_PCT 1.5
upsert SNAPSHOT_CACHE_SECONDS 3
upsert MARKET_POLL_SECONDS 3
upsert MARKET_SNAPSHOT_POLL_SECONDS 30
upsert BACKGROUND_MARKET_MONITOR_ENABLED true
upsert BACKGROUND_MONITOR_SCHEDULE_ENABLED false

echo "==> Key trading settings:"
sudo grep -E "^(PAPER_MAX_CATCH|PAPER_MIN_ENTRY|PAPER_HIGH_CONFIDENCE|EXPLOSIVE_RUNNER|MARKET_POLL|SNAPSHOT_CACHE)" "${ENV_FILE}" | sort -u || true
